#!/bin/sh

system_type=$(uname -s)
echo "${system_type}"

is_command() {
    command -v "$1" > /dev/null 2>&1
}

UNAME_MACHINE="$(/usr/bin/uname -m)"
if [[ "${UNAME_MACHINE}" == "arm64" ]]
then
    # On ARM macOS, this script installs to /opt/homebrew only
    HOMEBREW_PREFIX="/opt/homebrew"
else
    # On Intel macOS, this script installs to /usr/local only
    HOMEBREW_PREFIX="/usr/local"
fi

if [ -f "$HOME/.config/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --file=~/.config/Brewfile
fi
