server = "https://docker.io"

[host."https://jh5b28by.mirror.aliyuncs.com"]
  capabilities = ["pull", "resolve"]

[host."https://mirrors.saltbo.cn"]
  capabilities = ["pull", "resolve"]

[host."https://registry-1.docker.io"]
  capabilities = ["pull", "resolve"]
