[worker.oci]
  enabled = false

[worker.containerd]
  enabled = true
  namespace = "default"
  snapshotter = "overlayfs"

[registry."docker.io"]
  mirrors = ["jh5b28by.mirror.aliyuncs.com", "mirrors.saltbo.cn"]
